steps:
  - name: build-binaries
    image: golang:1.22.0
    commands:
      - mkdir -p ./artifacts
      - version="woodpecker"
      - appName="PortHog"
      - builtAt="$(date +'%F %T %z')"
      - gitCommit=$(git log --pretty=format:"%h" -1)
      - ldflags="-w -s -X 'main.AppName=$appName' -X 'main.BuiltAt=$builtAt' -X 'main.GitCommit=$gitCommit' -X 'main.Version=$version'"
      - GOOS=linux GOARCH=amd64 go build -ldflags="$ldflags" -o "./artifacts/porthog_linux_amd64" .
      - GOOS=linux GOARCH=arm64 go build -ldflags="$ldflags" -o "./artifacts/porthog_linux_arm64" .
      - GOOS=darwin GOARCH=amd64 go build -ldflags="$ldflags" -o "./artifacts/porthog_darwin_amd64" .
      - GOOS=darwin GOARCH=arm64 go build -ldflags="$ldflags" -o "./artifacts/porthog_darwin_arm64" .
    when:
      event: [ push, tag, manual ]

  - name: test-file
    image: alpine:latest
    commands:
      - cd artifacts
      - du -sh *
      - ls -all
    when:
      event: [ push, tag, manual ]